import { Upgrade, UpgradeType, CowDefinition } from './types';

export const TICK_RATE_MS = 100; // Game loop runs every 100ms
export const SAVE_KEY = 'steak_inc_save_v1';

export const INITIAL_STATE = {
  money: 0,
  cows: 0,
  currentCowIndex: 0,
  lifetimeEarnings: 0,
  startTime: Date.now(),
  purchasedUpgrades: {},
};

// Base Stats
export const BASE_STEAK_VALUE = 0.25;
export const BASE_COW_PRODUCTION = 1; // 1 steak per cow per sec
export const BASE_HOUSING = 50;
export const BASE_SHIPPING = 100; // Steaks/sec

export const COW_TYPES: CowDefinition[] = [
  {
    id: 'cow_holstein',
    name: 'Holstein',
    description: 'The classic dairy cow, repurposed for bulk steak production.',
    valueMultiplier: 1,
    color: '#ffffff',
    spotColor: '#000000',
    image: 'assets/holstein.png',
    unlockCost: 0,
  },
  {
    id: 'cow_angus',
    name: 'Black Angus',
    description: 'Renowned for quality beef. A solid step up.',
    valueMultiplier: 5,
    color: '#3e2723', 
    spotColor: '#1a1a1a',
    image: 'assets/blackangus.png',
    unlockCost: 100000, // 100k
  },
  {
    id: 'cow_wagyu',
    name: 'Wagyu',
    description: 'Highly marbled, highly expensive luxury beef.',
    valueMultiplier: 25,
    color: '#e57373', 
    spotColor: '#ffebee', 
    image: 'assets/wagyu.png',
    unlockCost: 50000000, // 50M
  },
  {
    id: 'cow_golden',
    name: 'Golden Bovine',
    description: 'Genetically engineered to produce literal gold flakes in the meat.',
    valueMultiplier: 150,
    color: '#fdd835', 
    spotColor: '#fff176',
    image: 'assets/goldenbovine.png',
    unlockCost: 10000000000, // 10B
  },
  {
    id: 'cow_cyber',
    name: 'Cyber Cow 2077',
    description: 'Synthetic meat grown on a chrome chassis. The future is flavor.',
    valueMultiplier: 1000,
    color: '#00bcd4', 
    spotColor: '#18ffff', 
    image: 'assets/cybercow.png',
    unlockCost: 1000000000000, // 1T
  }
];

export const UPGRADES: Upgrade[] = [
  // --- Habitats ---
  {
    id: 'hab_coop',
    name: 'Wooden Coop',
    description: 'A small shelter for your bovine friends.',
    baseCost: 15,
    costMultiplier: 1.8,
    effectValue: 50,
    effectType: 'add',
    target: 'housing',
    type: UpgradeType.HABITAT,
    tier: 1,
  },
  {
    id: 'hab_barn',
    name: 'Red Barn',
    description: 'The classic American icon. Spacious and breezy.',
    baseCost: 500,
    costMultiplier: 2.0,
    effectValue: 250,
    effectType: 'add',
    target: 'housing',
    type: UpgradeType.HABITAT,
    tier: 2,
  },
  {
    id: 'hab_warehouse',
    name: 'Cow Warehouse',
    description: 'Industrial grade living solutions.',
    baseCost: 5000,
    costMultiplier: 2.2,
    effectValue: 2000,
    effectType: 'add',
    target: 'housing',
    type: UpgradeType.HABITAT,
    tier: 3,
  },
  {
    id: 'hab_feedlot',
    name: 'Mega Feedlot',
    description: 'Optimized density for maximum occupancy.',
    baseCost: 150000,
    costMultiplier: 2.3,
    effectValue: 10000,
    effectType: 'add',
    target: 'housing',
    type: UpgradeType.HABITAT,
    tier: 4,
  },
  {
    id: 'hab_tower',
    name: 'Bovine Skyscraper',
    description: 'Vertical farming taken literally.',
    baseCost: 5000000,
    costMultiplier: 2.5,
    effectValue: 50000,
    effectType: 'add',
    target: 'housing',
    type: UpgradeType.HABITAT,
    tier: 5,
  },

  // --- Transport ---
  {
    id: 'trans_trike',
    name: 'Delivery Trike',
    description: 'Carry more steaks to market.',
    baseCost: 50,
    costMultiplier: 1.6,
    effectValue: 50,
    effectType: 'add',
    target: 'shipping',
    type: UpgradeType.TRANSPORT,
    tier: 1,
  },
  {
    id: 'trans_pickup',
    name: 'Pickup Truck',
    description: 'Reliable transport for reliable steaks.',
    baseCost: 1000,
    costMultiplier: 1.9,
    effectValue: 500,
    effectType: 'add',
    target: 'shipping',
    type: UpgradeType.TRANSPORT,
    tier: 2,
  },
  {
    id: 'trans_semi',
    name: 'Refrigerated Semi',
    description: 'Keep those steaks fresh across the country.',
    baseCost: 15000,
    costMultiplier: 2.1,
    effectValue: 5000,
    effectType: 'add',
    target: 'shipping',
    type: UpgradeType.TRANSPORT,
    tier: 3,
  },
  {
    id: 'trans_train',
    name: 'Freight Train',
    description: 'Massive logistical power.',
    baseCost: 250000,
    costMultiplier: 2.2,
    effectValue: 25000,
    effectType: 'add',
    target: 'shipping',
    type: UpgradeType.TRANSPORT,
    tier: 4,
  },
  {
    id: 'trans_rocket',
    name: 'Steak Rocket',
    description: 'Intercontinental ballistic delivery.',
    baseCost: 10000000,
    costMultiplier: 2.5,
    effectValue: 200000,
    effectType: 'add',
    target: 'shipping',
    type: UpgradeType.TRANSPORT,
    tier: 5,
  },

  // --- Research ---
  {
    id: 'res_feed',
    name: 'Nutritional Pellets',
    description: 'Better food makes for tastier steaks. +10% Steak Value.',
    baseCost: 100,
    costMultiplier: 2.5,
    effectValue: 0.10, // 10%
    effectType: 'multiply',
    target: 'value',
    type: UpgradeType.RESEARCH,
    tier: 1,
  },
  {
    id: 'res_breeding',
    name: 'Efficient Breeding',
    description: 'Cows appear faster when you call them. +1 Spawn/click.',
    baseCost: 250,
    costMultiplier: 3.0,
    effectValue: 1,
    effectType: 'add',
    target: 'hatchRate',
    type: UpgradeType.RESEARCH,
    tier: 1,
  },
  {
    id: 'res_marbling',
    name: 'Genetic Marbling',
    description: 'Intramuscular fat is where the money is. +25% Steak Value.',
    baseCost: 2000,
    costMultiplier: 4.0,
    effectValue: 0.25,
    effectType: 'multiply',
    target: 'value',
    type: UpgradeType.RESEARCH,
    tier: 2,
  },
  {
    id: 'res_massage',
    name: 'Auto-Massagers',
    description: 'Relaxed cows taste better. +50% Steak Value.',
    baseCost: 50000,
    costMultiplier: 4.5,
    effectValue: 0.50,
    effectType: 'multiply',
    target: 'value',
    type: UpgradeType.RESEARCH,
    tier: 3,
  },
  {
    id: 'res_cloning',
    name: 'Rapid Cloning',
    description: 'Why wait for nature? +5 Spawn/click.',
    baseCost: 500000,
    costMultiplier: 5.0,
    effectValue: 5,
    effectType: 'add',
    target: 'hatchRate',
    type: UpgradeType.RESEARCH,
    tier: 4,
  },
];